### ISSUE TITLE
Account for multiple Postmark streams

### ISSUE THREAD

**Issue by codyjames** [craftcms/postmark#11]
### Description
Postmark now has support for multiple "streams". The default "outbound" stream is used for transactional mail. They also now have a "broadcast" stream which is used for sending bulk email to folks (newsletters, etc.). We'd like to be able to use both. To do this, we'd need to add the stream to the Postmark API request.

We are using the [Campaign plugin](https://putyourlightson.com/plugins/campaign).

I _think_ if this plugin added an optional setting for the stream, we'd be able to set that in our default Craft mail settings as well as (with a different value) in the Campaign mail settings.

**Comment by acantes** [comment]
+1 for this feature. 

It would be great to connect a Postmark account to Craft CMS and then choose a specific message stream to be used for transactional emails and a different message stream to be used for Campaign send-outs. Postmark is a dream to use and this seems like a logical and potentially frequent use-case.

**Comment by bossanova808** [comment]
+1 

I'm currently with Mailgun but would prefer to move to Postmark - but can't really effectively  do so until we can send both transactional emails and our newsletter (also using Campaign) - and to do that we'd need streams support it seems.

**Comment by brandonkelly** [comment]
@bencroker Does Campaign use Craft’s built-in Mailer?

**Comment by bencroker** [comment]
Yes, it does @brandonkelly:
https://github.com/putyourlightson/craft-campaign/blob/1.17.3/src/Campaign.php#L281-L288

**Comment by brandonkelly** [comment]
v2.1.0 is out now with support for specifying a custom Message Stream (thanks to @matt-west / #12).

Craft only has one `mailer` component, and mail transporters play a supporting role in that, so I’m not sure how a transporter like the Postmark plugin could add support for _multiple_ streams. If Campaign wishes to add support for multiple streams, then Campaign would need to add its own Postmark integration. That said, maybe #12 is good enough, as a broadcast stream can also be used for transactional email (per https://github.com/craftcms/postmark/pull/12#issuecomment-776756678).

**Comment by bossanova808** [comment]
Thanks for this.

The issue with broadcast vs. transactional is all about sender reputation.  In an ideal world, while there might be no _technical_ reason that transactional can't be sent on the broadcast stream, the idea, I believe, is that one keeps the transactional (truly essential) stuff separate from marketing so that the best possible reputation (and thus deliverability) is achieved for the really important stuff, but the marketing stuff (where people are much more inclined to hit that 'spam button at the drop of a hat, and auto spam systems like Spam Cop are much more likely to kick in just based on heuristics - and thus reputation can suffer even if one is entirely doing the right thing and mailing people things they've actually definitely opted in for... ) - is kept nicely separate.  For store owners, in particular then, keeping these two things quite separate is the ideal scenario.  Apologies if that is obvious.

Hopefully @bencroker might thus consider adding such support to the truly wonderful plugin that is Campaign.

**Comment by bencroker** [comment]
This should work nicely with Campaign, as the plugin allows you to select a mail transporter that is different from, or the same as but with different settings, the mail transporter set up in Craft. Have you tested this @bossanova808?

**Comment by brandonkelly** [comment]
Ah, well then perfect!

**Comment by bossanova808** [comment]
Not yet - haven't tested it yet as I didn't realise it was possible :) @bencroker  - first need to set up Postmark properly.  But sounds great to me!
