### ISSUE TITLE
Update broke my adapter

### ISSUE THREAD

**Issue by skarges3** [craftcms/postmark#9]
Since updating to version 2, craft's system cannot send email at all when Postmark is selected as the mailer. (e.g. account activation emails or the test button in email settings)

**Comment by joshuabaker** [comment]
This happened to me too. Something’s not quite right with the 1.x → 2.x update.

These steps worked for me...
1. `composer remove flipboxfactory/craft-postmark`
1. `composer require craftcms/postmark`
1. Removing `config/postmark.php`
1. Manually setting the Postmark token as an environment variable (so that it doesn’t end up in `project.yaml`)
